# Generated by Django 2.1 on 2018-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('descr', models.TextField()),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('run', models.IntegerField(max_length=8)),
                ('nombre', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('paterno', models.CharField(max_length=15)),
                ('materno', models.CharField(max_length=15)),
                ('fnac', models.DateTimeField()),
                ('telefono', models.CharField(max_length=9)),
                ('region', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('vivienda', models.CharField(max_length=10)),
            ],
        ),
    ]
