# Generated by Django 2.1 on 2018-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.IntegerField(),
        ),
    ]
