# Generated by Django 2.1.2 on 2018-11-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0002_auto_20181025_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatados',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
