# Generated by Django 2.1.2 on 2018-11-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0005_auto_20181107_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fnac',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='materno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='paterno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='snombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vivienda',
            field=models.CharField(max_length=10),
        ),
    ]
