# Generated by Django 2.1.2 on 2018-11-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0007_auto_20181108_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
