# Generated by Django 2.1.2 on 2018-11-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0009_auto_20181108_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
