# Generated by Django 2.1.2 on 2018-11-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_misperris', '0011_auto_20181108_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('foto', models.ImageField(upload_to='./media/imagenes/')),
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=30)),
                ('descr', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='Rescatado', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Rescatados',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
